- examples/demo-bind-to-single-property-async.html
- examples/demo-bind-to-single-property.html
- examples/demo-disable-search.html
- examples/demo-event-on-select.html
- examples/demo-groupby.html
- examples/demo-multi-select.html
- examples/demo-tagging.html
- examples/demo.html
- examples/select2-bootstrap3.html
- examples/selectize-bootstrap3.html
- src/bootstrap/choices.tpl.html
- src/bootstrap/match.tpl.html
- src/bootstrap/select-multiple.tpl.html
- src/bootstrap/select.tpl.html
- src/select.js
- src/select2/choices.tpl.html
- src/select2/match.tpl.html
- src/select2/select-multiple.tpl.html
- src/select2/select.tpl.html
- src/selectize/choices.tpl.html
- src/selectize/select.tpl.html
- test/select.spec.js
> Add acessibility

- src/select.js
This addresses issue #624, which is specific to tagging. I verified the change against the basic demo.html file and there is no impact.
To @brianfeister's comment in #624, I tested successfully ```tagging-label="{whatever}"``` and ```tagging-label="false"``` using the two first sections in demo-tagging.html.
> Issue/#624 - Add extra handling for negative activeIndex.

- src/select.js
- test/select.spec.js
Issue #485 solution. Handle paste event, then split string by tokens and try to add each item. Tokenization function will be apply to each item separately.
> Parse tags on paste from clipboard

- src/bootstrap/match.tpl.html
- src/select.css
> Fix broken bootstrap css styles

- src/select.css
Was introduced in 230216516ce5d929665e4089a45cab9ea3ed2f69
Since the comment is preserved my minifiers this wastes some bytes if the file is directly included.
> Remove duplicate file comment in select.css

- src/select.js
Hi,
I set up a small fix, so one could use data-* attributes for `ui-select-match` and `ui-select-choices`.
After this fix, something like this is possible:
```
<div data-ui-select data-ng-model="vm.selectedItem" data-theme="bootstrap" data-reset-search-input="false">
<div data-ui-select-match data-placeholder="select sth...">
{{ $select.selected }}
</div>
<div data-ui-select-choices data-repeat="item in vm.possibleItems| filter: $select.search">
<span data-ng-bind-html="item | highlight: $select.search"></span>
</div>
</div>
```
Without the fix this code causes Google Chrome to hang (some JS goes into the loop, probably the one described in the comment on line 1179 and 1186). With the fix it just works, and one can have a HTML5-validatable template.
> Properly handle HTML5 data-* attributes

- src/select.js
If the ngModel is defined and an angular version with $touched is used, the select will mark the ngModel as touched when the list closes, to make it consistent with the native select control.
> supports Angular 1.3's $touched attribute on close

- examples/demo-tagging.html
- examples/demo.js
- src/select.js
This pull request addresses the issue https://github.com/angular-ui/ui-select/issues/597
I have included a sample demo code as well.
Thanks,
> Enable tagging without multi selection (see #597)

- src/bootstrap/match.tpl.html
- src/select.js
- src/select2/match.tpl.html
- test/select.spec.js
Demo [plunker](http://plnkr.co/edit/vtOWB1y2esheyryeq1aO?p=preview)
> fix(bootstrap): allow-clear style

- src/select.js
Not working [Plunker](http://plnkr.co/edit/o7JC4bFWIf0KpcnzxGIQ?p=preview)
Fixed [Plunker](http://plnkr.co/edit/mLIvTBnL8voBLekPayQE?p=preview)
Not working [Plunker](http://plnkr.co/edit/MQ1VuldDLsm6GDNPMEXU?p=preview)
Fixed [Plunker](http://plnkr.co/edit/uvfqngiOclpE47fvXHvh?p=preview)
Fixes #283 , Fixes #253, Fixes #598, Fixes #646
> fix(focus): prevent focus stealing when clicking on other ui-select element

- src/select.js
- test/select.spec.js
Rebase of @alexcrown PR https://github.com/angular-ui/ui-select/pull/663
> fix(tagging): allow to decline tag creation

- src/uiSelectController.js
- src/uiSelectDirective.js
Fix issue with the sizing of the text input field when the visibility of the input control is dynamically toggled, for example via the `ng-disabled` attribute on the `<ui-select>` element.
The problem is caused by the width calculation getting an incorrect 0 `offsetLeft` value for the input, as the `offsetParent` of the input is still `null` when the controller tries to calculate the width. The fix resolves this by adding a watch for the `offsetParent`, and only performing the width calculation when both the `offsetParent` *and* the container width are available.
I've created a Plunk to demonstrate the issue:
http://plnkr.co/79Ajy18oWP88EopEKAmn
And here's the same example, but with the patch applied:
http://plnkr.co/KdsdBldLBwLRfojjWY24
I've reproduced the problem in Safari, Chrome, …
> Fix issue with the sizing of the text input field

- src/uiSelectDirective.js
The search input size was being calculated incorrectly for non-multiple select instances using the Bootstrap theme. Remedy by only calling the sizing function when the select is in multi mode, which is how this function is guarded on other call sites as well.
Check out the Bootstrap select field on the `demo.html` page to see the problem in action.
> Fix for sizing bug introduced by #718

- examples/demo-append-to-body.html
- examples/demo.js
- src/common.css
- src/common.js
- src/uiSelectDirective.js
- test/select.spec.js
Add an `append-to-body` attribute to the `<ui-select>` directive that moves the dropdown element to the end of the body element before opening it, thereby solving problems with the dropdown being displayed below elements that follow the `<ui-select>` element in the document. This implementation is modeled after the `typeahead-append-to-body` support from UI Bootstrap, but adds the whole select element to the body, not just the dropdown menu, which is needed for the Select2 theme. See #41 (and quite a few dupes).
This replaces my previous PR #718 which did not work with the Select2 theme.
> Add an append-to-body attribute to <ui-select>

- src/bootstrap/match-multiple.tpl.html
- src/bootstrap/select-multiple.tpl.html
- src/common.css
- src/select2/match-multiple.tpl.html
- src/select2/select-multiple.tpl.html
- src/uiSelectChoicesDirective.js
- src/uiSelectController.js
- src/uiSelectDirective.js
- src/uiSelectMultipleDirective.js
- src/uiSelectSingleDirective.js
- src/uisRepeatParserService.js
- test/select.spec.js
Recently we started organizing the library on https://github.com/angular-ui/ui-select/pull/684 when code was separated into multiple files, but I still see too much  conditional code to check if the component is on single/multiple selection mode. So I think that will be better to split the code into 2 different directives, `uisSingle` and `uisMultiple` respectively that will internally be appended to the element automatically on main `uiSelect` compile fn, depending on the presence or absence of `multiple` attribute.
PD: the public API wont change, its just internal
New files created:
* uisSingleDirective.js
* uisMultipleDirective.js
> chore(refactor): split code into multiple directives

- src/uiSelectDirective.js
Fixes for two issues with the append-to-body functionality (see #736).
Here's a screenshot showing the results of “misplacing” the invocation of `transcludeFn`.
> Fix issues with append-to-body

- src/uiSelectMultipleDirective.js
Closes https://github.com/angular-ui/ui-select/issues/739
Fixed [plunker](http://plnkr.co/edit/0IDbtL?p=preview)
Closes https://github.com/angular-ui/ui-select/pull/410
> fix(multiple): formatter binding

- src/uiSelectController.js
Clearing selection can result in $rootScope:inprog error when focus() is called and an $apply is already in progress. 
Fixed as described in https://docs.angularjs.org/error/$rootScope/inprog
> Wrap focus in timeout to prevent Error: $rootScope:inprog

- src/uiSelectController.js
- test/select.spec.js
Fix the event propagation when pressing enter or escape key from dropdown
Run the tests and try the demos
https://github.com/angular-ui/ui-select/issues/862
> Stop propagation when pressing ENTER or ESC key from dropdown

- examples/bootstrap.html
- examples/select2-bootstrap3.html
- examples/selectize-bootstrap3.html
- src/bootstrap/choices.tpl.html
- src/common.css
- src/select2/select-multiple.tpl.html
- src/select2/select.tpl.html
- src/selectize/choices.tpl.html
- src/uiSelectDirective.js
This addresses issue #148, which relates to how the dropdown displays in the event there isn't enough space to render it fully.  An up direction has been added.
I verified the change against demo.html, demo-multi-select.html and the three theme html files.
> Issue #148 - Add up direction to dropdown rendering.

- src/uiSelectDirective.js
Resolves #1032 by hiding the element with opacity, not
visibility. Elements with an opacity of 0 can still be focused.
> Use opacity, not visibility to hide element

- package.json
This should be an user action, not something automatically run on install.
We're using ui-select in a browserify project, and we don't need/have bower installed. Furthermore it pollutes the development folder with an unused bower_components.
> Do not run bower after install automatically

- examples/demo.js
Move ‘var keys = Object.keys(props);’ outside of the items.forEach(…)
loop. As previously written, keys will be re-instantiated on every
iteration of the forEach loop.
> chore(code clean-up): optimize propsFilter

- src/uiSelectDirective.js
As scope() isn't available when debug info is disabled, use controller() to retrieve a controller from an element
Fixes #872
> fix(uiSelect): typing goes on last focused component

- src/uiSelectDirective.js
It is dangerous to assume that `dropdown` will only be `null`. angular.element returns an empty array when no elements have been found.
> Dropdown can also be an empty array

- src/uiSelectController.js
- src/uiSelectDirective.js
To avoid incorrect dropdown position
Wrong [Demo](http://plnkr.co/edit/oZCudVaPNc42B7hLYB7j?p=preview)
Corrected [Demo](http://plnkr.co/edit/vElyF6gmKYXA6jiM1K1k?p=preview)
*To reproduce, scroll down to red field*
> fix(dropdown): cross browser dropdown position

- examples/demo-object-as-source.html
- examples/demo.js
- src/uiSelectChoicesDirective.js
- src/uiSelectController.js
- src/uisRepeatParserService.js
- test/select.spec.js
We'll be able to use an object as the source for the choices (iterating over its properties)
Demo [plunker](http://plnkr.co/edit/9DsLidTZR7RJDEq6PW0H?p=preview])
Pending:
> feat(choices): use object as source iterating over its properties

- src/common.css
- src/uiSelectChoicesDirective.js
- src/uiSelectController.js
- test/select.spec.js
We were using `ng-mouseenter` to be able to set the hovered row as the active item, but this caused some lagging as `ng-mouseenter` was calling for a full $digest.
Could be better just to show a simple hover background change (using css) and avoid doing a $digest.
Demo [plunker](http://plnkr.co/edit/1Nl9SBsc1yoxO3xDSZQk?p=preview)
> refactor(choices): avoid setting activeItem on mouseenter

- examples/demo-dropdown-position.html
- src/common.js
- src/uiSelectChoicesDirective.js
- src/uiSelectController.js
- src/uiSelectDirective.js
We should be able to set dropdown position explicitly so I added a new attribute called `position` for the `<ui-select-choices>` tag, that will accept 3 values: *up*, *down* and *auto*
Sometimes we might not want the dropdown to go automatically up even when there isn't enough space, so now we can force position to always go to an specific direction.
Also you can specify globally at `uiSelectConfig` using `dropdownPosition`
Demo [plunker](http://plnkr.co/edit/J8plv8vnnrzFV61Pkpls?p=preview)
> feat(choices): allow to set default dropdown position

- src/uiSelectDirective.js
- test/select.spec.js
fixes https://github.com/angular-ui/ui-select/issues/1195
fixes https://github.com/angular-ui/ui-select/issues/236
> add input id to search <input> if present on ui-select directive as input-id

- src/common.js
- test/select.spec.js
We had a bunch of exceptions caused by using the `highlight` filter on a list of years.  This PR casts numeric items to strings to fix this.  Includes a test to verify normal behavior and one verifying the fix.
> make highlight filter work with numeric items

- src/bootstrap/choices.tpl.html
If a server sets the `content-security-policy` header to `script-src 'self' 'unsafe-inline';` all works well, but without `unsafe-unline`, the browser will throw an error: `Refused to execute JavaScript URL because it violates the following Content Security Policy directive:`.
There is no stack trace, but it turns out this is caused by `href="javascript:void(0)"` in the choices template. 
Pull request #395 proposed removing that piece Javascript altogether, but apparently there were side effects.
I'm replacing it with `ng-click="$event.preventDefault()"`, based on a similar fix in the [ui.bootstrap](https://github.com/angular-ui/bootstrap/commit/fb302c6086543420b3561be3ed5c49ac3974c243) project. This makes the CSP error go away.
All tests pass. I tried all examples in Safari and couldn't …
> Avoid inline execution of javascript in choices template.

- src/bootstrap/choices.tpl.html
https://github.com/angular-ui/ui-select/commit/4467b8238866f85003f8815f44a7ca8563222043 made the cursor not change into a hand when hovering over an item because the a doesn't have an href.
This pull request removes the ng-click with prevent default because an empty href in angular does exactly the same. See: https://docs.angularjs.org/api/ng/directive/a
Here is an example of the current master version: http://plnkr.co/edit/O2tbRRFOC0IDwHI363cM?p=preview
And here is an example with this change: http://plnkr.co/edit/MXW3abVF9l0fzYElYDv1?p=preview
> Fix broken ng-click

- src/uiSelectMultipleDirective.js
A bug was caused when _findApproxDupe was trying to set "isTag" property on a privitive value (e.g. String). These types of values are received when $select.selected holds an array of privitive values (using key binding).
**Link to a [proof of concept](http://plnkr.co/edit/yCGBkcsfl6m9ib4Tuyo4?p=preview)**
> Fix _findApproxDupe when using tagging function and property binding features together on iuSelectMultiple.

- src/uiSelectController.js
When dealing with a list of object values, indexOf isn't always sufficient for accurately finding the activeIndex.  This patch uses findIndex instead of indexOf to look up the activeIndex.
> use findIndex instead of indexOf when looking up activeIndex

- src/uiSelectDirective.js
fix: stop select from closing
Stop select from closing when focusing it from ui-select
Closes #1408
> Fixes #1408

- src/uiSelectChoicesDirective.js
- src/uiSelectMatchDirective.js
- test/select.spec.js
In Angular 1.5, transcluded content is linked lazily.
For uiSelect that means the clone in the transclude function is not compiled and linked yet, so
uiSelect cannot detect the match and choices elements by their classnames, because they haven't been
set yet (which happens by replacing the elements with the templates).
However, the templateUrl function is executed at this point, so we can use it to add the
class names to the directive elements.
On another note, this behavior also affected versions earlier than 1.5.0-beta.2, when the template
of ui-select-match or ui-select-choices wasn't cached. In that case, the async compilation of
the template would mean also that the clone in the transclude function wasn't compiled yet, and so
the classes wouldn't be set either.
Closes #1422
Closes …
> fix: make compatible with Angular 1.5 and non-cached templates

- src/uiSelectDirective.js
Since a ngClass is already present in the uiSelect theme templates, we could not add any ngClass on <ui-select> without getting an JS error
Currently, adding a ngClass on <ui-select> result in:
`ng-class="{class: expression} {open: $select.open}"`
With this fix, doing the same thing result in:
`ng-class="{class: expression, open: $select.open}"`
Closes #277
Maybe I should write a test case ?
> fix: Allow setting a ngClass on <ui-select> element

- src/uiSelectSortDirective.js
> fix(uiSelectSort): fix dependency not found error

- src/uiSelectController.js
- src/uiSelectDirective.js
- test/select.spec.js
Add paste="expression" to allow custom paste handling.
Allow pasting in tagging mode when the tagging function is not defined.
In IE use window.clipboardData so jQuery is not required.
Fixes #910, #704, #789, #848, #429
> Add proper paste support

- src/uiSelectDirective.js
When an appendToBody is true, the whole select field is literally moved within the DOM when the dropdown is triggered.  When the user has focus in the textbox, and the dropdown disappears, the textbox loses focus.
This is a problem when you have a user that is "delete" trigger happy, as they then navigate back in history.
This pull request sets focus on the dropdown text field when the dropdown disappears.
> fix appendToBody focus on dropdown close #1003

- src/uiSelectChoicesDirective.js
https://github.com/angular-ui/ui-select/issues/158, based on an observed (but maybe not well understood) code change by @careywalker. Basically, just move the ng-click/ng-mouseenter bindings from the LI (choices-row) to the contained DIV (choices-row-inner). So far, I haven't seen an affect on behavior in any browser, but this is with light manual testing.
All automated tests pass with these changes in place:
>gulp test
[15:05:36] Using gulpfile C:\web\sites\ui-select\gulpfile.js
[15:05:36] Starting 'clean'...
[15:05:36] Finished 'clean' after 14 ms
[15:05:36] Starting 'scripts'...
[15:05:36] Starting 'styles'...
[15:05:36] Finished 'styles' after 61 ms
[15:05:37] Finished 'scripts' after 1.01 s
[15:05:37] Starting 'build'...
[15:05:37] Finished 'build' after 14 μs
[15:05:37] Starting …
> Fix for selects not working in IE8

- src/uiSelectController.js
- src/uiSelectMultipleDirective.js
This is the same pull request as #647 without the dist/ files.
> fix(uiSelectMultipleDirective): Fixes checks for existing tags during multiple tag creation and selection

- CHANGELOG.md
- package.json
- src/uisRepeatParserService.js
- test/select.spec.js
Simple repeat expressions that used track by failed.
```html
<ui-select-choices repeat="question in questions track by question.question_id"...>
```
The previous regex attempted to extract the filters from the expression but greedily included the track by portion too. The filters, however, are only needed when using an object as a source as `ui-select` needs to manually apply them when converting the object to an array. 
Now the repeat parser will extract the source expression in one lump and let `$parse` deal with it if it can, only if an object source is used, will it attempt to extract the filters. 
This more closely aligns `ui-select` with `ngOption`'s parsing/regex (though it doesn't need to extract any filters). 
Fixes #1233 #1462 #1263 #1270
>_Apologies if the regex is a bit messy …
> fix(parser) allow track by without filter

- src/bootstrap/choices.tpl.html
In some cases dropdown is shown even when it is not open. That's because ng-show is bound to $select.items, that may be not empty.
> Updated choices.tpl.html to properly hide and show dropdown

- CHANGELOG.md
- package.json
- src/common.js
- src/uiSelectChoicesDirective.js
- src/uiSelectController.js
- src/uiSelectDirective.js
This PR provides a new feature to be able to configure skipping the focusser after selecting an item.
After much trying I have unfortunately not found a way to cover the changes with the necessary unit tests. Focusing and testing the involved elements for focus proved more complex than I thought...
> Configure skip focusser

- test/select.spec.js
References PR #1447
- Add missing test on uiSelect when merging ngClass attributes between DOM declaration and template
- Add one property `attrs.ngClass` in `createUiSelect(attrs)` to append a `ng-class` attribute to the `<ui-select>` element
> test(uiSelectDirective): Add test when merging ngClass attributes on uiSelect

- src/bootstrap/select-multiple.tpl.html
- src/bootstrap/select.tpl.html
- src/select2/select-multiple.tpl.html
- src/select2/select.tpl.html
- src/selectize/select.tpl.html
Edge browser showed autocomplete with autocomplete=false Standard states
it should be autocomplete=off which works currently with Chrome too.
Closes #1346
> Fix(templates): Autocomplete=false does not work in Edge

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
This updates the contributing guidelines to include some text about how to open bugs or feature requests. The idea is we can close issues which get opened without following the guidelines.
Also adds an issue template.
> chore(contributing): update contributing doc and issue template

- src/uiSelectController.js
The dropdown was going back to the activated element ('A' for instance) when the user clicked on the 'X' element, which was quite annoying when he wanted to select also Y and Z
cf #976
> fix the PR #1208 which had broken the multiple selection ordered by groups

- karma.conf.js
- package.json
Angular, Angular Sanitize, Angular Mocks and JQuery.
Removed: post-install bower script. No longer need to call bower from npm.
This will help when you guys decide to publish the package in NPM.
> Use npm to install required dependencies to run the tests.

- src/uiSelectMultipleDirective.js
- test/select.spec.js
This is basically the same with #1243, but comes with the test for the fix.
Thanks for your hard work of maintaining this great library!
> fix(uiSelectMultipleDirective): refresh choices upon selection change

- src/uiSelectChoicesDirective.js
setActiveItem was removed as part of PR #1211 but not all calls to the function were.
> refactor(uiSelectChoices) remove setActiveItem refs

- src/uiSelectController.js
Corrected input focus when ui-select contains no elements. Also corrected a memory leaked caused by event handlers never being removed.
Closes #1253
> fix(uiSelectCtrl): correcting input focus

- src/uiSelectMatchDirective.js
- test/select.spec.js
uiSelectMatch was a special case where the non-normalised `multiple` attribute is checked, therefore using `data-multiple` resulted in the single select match template being loaded instead of the multiple-select-match template.
test is more involved than I would have liked but I couldn't see any other way to test it. 
Closes #1451
> fix(uiSelect) support data-multiple attribute

- src/uiSelectChoicesDirective.js
- test/select.spec.js
After doing memory leak hunting in my application I found that ui-select is leaking memory. I'm not sure why this is exactly needed as I would have expected $compile to handle it (I tried looking at uiSelectDirective.js with no results)
> Fix angular.element.cache memory leak

- README.md
- bower.json
ui-select is a different package, angular-ui-select is the correct
package name.
> chore(bower) update package name

- src/bootstrap/no-choice.tpl.html
- src/bootstrap/select.tpl.html
- src/common.css
- src/uiSelectDirective.js
- src/uiSelectNoChoiceDirective.js
I'm using ui-select in my project as it's a cool component. In my project, I really need the ability to show information when there is no record found. Looks like it's not implemented yet so I'm pushing this pull request for discussion.
I would like to create a separate directive (uiSelectNoChoice) to specify a template to be displayed when there is no record.
We can use it like this:
```
<ui-select ng-model="address.selected"
theme="bootstrap"
ng-disabled="disabled"
reset-search-input="false"
style="width: 300px;"
title="Choose an address">
//remove others for a clearer view
<ui-select-no-choice>
<div style="text-align: center;">There is nothing to show</div>
</ui-select-no-choice>
</ui-select>
```
At the moment, I only implement it for bootstrap theme (for discussion purpose). If you …
> New feature: allow displaying information when there is no record found

- src/common.js
This fix prevents ui-select from catching keystrokes when ctrl or alt is pressed. For example, when a field has focus, pressing ctrl-enter will no longer result in opening the dropdown. This way the webpage can use these shortcuts without ui-select stealing them away.
> Fix: ignore metakeys when field has focus but dropdown is closed

- examples/demo-tagging.html
- src/uiSelectMultipleDirective.js
- test/select.spec.js
This pull-request includes:
* Fixed tagging to work with group-by (and added a unit test) (fixes https://github.com/angular-ui/ui-select/issues/577)
* Fixed a unit test `should allow decline tags when tagging function returns null` to catch an error and fixed that error (`Cannot set property 'isTag' of null`)
* Removed needlessly calling the tagging function (and added a unit test)
* Fixed a console error in [demo-tagging example](http://rawgit.com/angular-ui/ui-select/master/examples/demo-tagging.html). When entering `a` into Object Tags input, highlight filter replaced `<small>` with `<sm<span class="ui-select-highlight">a</span>ll>`
> Fix tagging with group-by (and unit-tests)

- src/bootstrap/choices.tpl.html
- src/select2/choices.tpl.html
- test/select.spec.js
The id attribute on ui-select-choices-row is no longer interpolated correctly when using ui select with angular v1.5+.
This change switches to using ng-attr-id to ensure the id value is correctly interpolated before being assigned to the element.
Fixes #1522
> fix(uiSelectChoices) broken id interpolation

- .travis.yml
- README.md
Following merge of #945 bower is not longer required for development, this commit removes it from travis build and dev setup docs.
> chore(ci) remove bower dev references

- src/uiSelectController.js
- Optimize running dynamic width calculations when resizing
This is not the right way for updates to be made to the input size in general, but this is a vast improvement over the current method. The improvement here is that it does not touch the DOM until after everything stabilizes in the dirty checking loop, so it avoids the expensive DOM check in the watch expression callback until the end.
> feat(perf): optimize width resizing

- src/uiSelectChoicesDirective.js
Previously the template was compiled, edited, and then recompiled. This was unecessary as the changes we unrelated to the scope and so could be made before the link function was run.
This change, moves the DOM transformations to the compile function so the directive does not have to be compiled manually.
Fixes #1000
> refactor(uiSelectChoices) only compile template once

- docs/partials/_header.html
- gulpfile.js
filenames plugin appeared to be causing header and footer additions to be run twice.
Also removes dodgy character at start of header html partial
> docs(examples) fix double header/footer wrapping

- src/bootstrap/match.tpl.html
This addresses this issue: https://github.com/angular-ui/ui-select/issues/980 
> Clear button shown on disabled select
This will hide the clear button if $select.disabled is true.
> hide clear button if disabled

- README.md
- docs/index.html
Currently the npm module name in the readme is wrong.
We've run into incompatibility issues because of that. (same error like in #224)
Can somebody also deprecate `angular-ui-select` on npm and point to the new name of the module, please.
This pr fixes #1574
> Update npm package name in readme

- src/select2/select-multiple.tpl.html
this is equivalent to #1588 for bootstrap
the empty dropdown behaviour was especially annoying when using ui-select for tagging without choices.
> fix(select2): hide dropdown if there are no items to show

- src/bootstrap/select-multiple.tpl.html
while using ui-select-no-choice directive it doesn't apply for multiselect mode (bootstrap theme). Appropriate markup was missed for multiselect mode in template for bootstrap theme.
fix for #1614
> template fix for ui-select-no-choice directive

- docs/assets/demo.js
- docs/examples/demo-multiple-selection.html
- src/common.js
- src/uiSelectController.js
- src/uiSelectDirective.js
- src/uiSelectMultipleDirective.js
- test/select.spec.js
Expose and implement `remove-selected="false"` for multiple selects. This will disable a choice
in the dropdown of a multiple-select element instead of removing it.
Sample behavior:
In the existing version, `id` would not have appeared in the dropdown because it is currently selected. This pull request adds the option `removeSelected` so that, if set to `false`, selected items still appear in the dropdown but are disabled (like in the screenshot).
> feat(removeSelected): Implement removeSelected property for multiple selects

- src/uiSelectDirective.js
When calculating the dropdown position the height of the dropdown
needs to be known. When using ngAnimate the animation has not
finished by the time the height calculation is needed. This fix
extracts the positioning calculation out to a function that is
called after animation is done (or immediately when animation is
not in use).
Fixes #1593.
> fix(positioning): wait for animation to complete

- src/uiSelectController.js
Fixed an issue introduced by d78ba5f8f6e700143bdf3af1bfda0c05153daf45
The watcher was called only once since `angular.noop` will always return `undefined`.
Fixed this by calling the resize function on each `$digest` cycle.
Closes #1618
Closes #1617
Closes #1575
> fix: search input width resizing

- src/common.css
Just added a `display: inline-block` to the @rzschech [solution](https://github.com/angular-ui/ui-select/issues/933#issuecomment-116773277).
Fix #933
> 933 Fix text overflow in placeholder and match text

- src/uiSelectController.js
fix(uiSelectCtrl): change condition that checks if data is empty before applying filter
Error `Cannot read property 'filter' of null` occurs after initializing ui-select
> Cannot read property 'filter' of null

- src/uiSelectController.js
- test/select.spec.js
> fix(tagging): Support paste with tagging enabled and tagging-label="false"

- docs/assets/demo.js
- src/uiSelectController.js
- test/select.spec.js
Make sure that `removeSelected` only affects `multiple`s, include unit test, and add comment in demo examples.
Addresses #1672 and possibly #1681
> fix(removeSelected): fix incorrect removal of preselected item

- src/uiSelectMultipleDirective.js
- test/select.spec.js
Originally authored by homerjam
Closes #967 and #1686
Supersedes #1035 #1529 #1687
> fix(uiSelectMultiple): tolerate null/undefined model value

- .travis.yml
Build of docs was broken when npm releases were automated.
Fix travis so docs are built and deployed on a new tagged release.
> build(docs) ensure docs are built on new release

- src/uiSelectController.js
- src/uiSelectMultipleDirective.js
- test/select.spec.js
Refactors isDisabled and isLocked to no longer rely on modifying the list item with `_uiSelectChoiceDisabled` and `_uiSelectChoiceLocked` properties which caused issues when items were used elsewhere (outside of the `ui-select` directive). 
Also, resolves infinite digest loop caused by attempting to add a new tag that included an existing tag, ie: 
``` 
tag1: "a"
tag2: "aa"
```
Closes #1200, #1661, #1693, #1269, #514
Closes #1641 and #952 (supersedes)
> Fix is disabled and prevent modifying items

- src/uisRepeatParserService.js
By using "track by", existing items don't have to be re-rendered when the array changes.
> Track groups by their name - Fix issue #1721

- src/uiSelectController.js
- test/select.spec.js
When in tagging mode, not multiple (taggingLabel === false), selecting an item by click was instead calling taggingFunc(). This fix checks
for this manual selection, whether ctrl.search is filled or not and
acts accordingly.
Same changes made in #1439 that were mysteriously lost.
Closes #1496
> fix(uiSelectController): Select by click on non-multiple tagging (bis)

- docs/examples/demo-disable-search.html
- src/bootstrap/select.tpl.html
- src/common.css
- src/select2/select.tpl.html
- src/selectize/match.tpl.html
- src/selectize/select.tpl.html
- src/uiSelectController.js
- test/select.spec.js
**fix(searchEnabled): maintain keyboard nagivation**
- Keyboard navigation stopped working when search-enabled="false"
- Fixes #1059, fixes #917, fixes #589, fixes #375
- Closes #1543, closes #1114, closes #1109 (supersedes all)
**fix(selectize): show placeholder when search disabled** 
- Selectize theme was missing placeholder when search-enabled="false"
- Fixes #1145, fixes #949, fixes #691
**fix(searchEnabled): Prevent searching when disabled**
- User's were still able to type and filter when search-enabled="false"
> Fix numerous issues with select enabled

- src/common.css
In bootstrap theme, if you have a ui-select with a given width and a long selected option it can overflow its box.
Reproduced with most recent versions at https://plnkr.co/edit/eHUcO3gdTY86owCOXL18?p=preview .
angularjs 1.5.7, bootstrap 3.3.6, ui-select 0.18.0
> fix(bootstrap layout): Restrict selected length to ui-select-container

- src/uiSelectController.js
Setting clickTriggeredSelect to true for "touchend" events fixes an issue I've encoutered when using this property in a search box (using ui-select-match and ui-select-choices), where we couldn't distinguish typing from clicking on an autocomplete result on mobile devices.
> Set clickTriggeredSelect to true for touchend events

- src/uiSelectController.js
Previously when the lock expression value changes from true to false the locked value was not removed from the locked list.
> fix(_updateItemLocked) properly unlock locked items when lock conditions change

- docs/partials/_header.html
When accessing https://angular-ui.github.io/ui-select/demo-tagging.html, the browser blocks insecure (http://) content.
> Load CDN assets over HTTPS

- src/uiSelectChoicesDirective.js
Previously, the .ui-select-choices-row element got deleted whenever the linked scope got destroyed which prevents rendering of the options in some cases.
> fix(uiSelectChoices): prevent template element from being modified

- test/select.spec.js
Angular 1.6 alters the way uncaught promises are handled - errors cause promise rejection rather than outright exceptions to be thrown.  Update existing exception tests to use the exceptionHandler service instead of `.throws()`
Closes #1877
> fix(spec): Use exceptionHandler to test errors.

- test/select.spec.js
For now i'm reverting these changes. As i believe this a problem (at this moment).
Needs some more investigation why this is happening and how to resolve it. 
#1916
> fix(unit tests) Changes for angular 1.5+

- src/common.css
- src/common.js
- test/select.spec.js
> fix(spinner-class): add glyphicon to default spinner class, update css

- src/uiSelectController.js
- test/select.spec.js
in case if items source is not defined in $scope when initializing multiselect instance of ui-select, we'll get an undefined from ctrl.parserResult.source($scope). then next line will throw an exception when truing to filter undefined.
> set default value to empty array

- docs/examples/demo-header-and-footer.html
- src/bootstrap/choices.tpl.html
- src/bootstrap/footer.tpl.html
- src/bootstrap/header.tpl.html
- src/bootstrap/select-multiple.tpl.html
- src/bootstrap/select.tpl.html
- src/common.css
- src/select2/footer.tpl.html
- src/select2/header.tpl.html
- src/select2/select-multiple.tpl.html
- src/select2/select.tpl.html
- src/selectize/choices.tpl.html
- src/selectize/footer.tpl.html
- src/selectize/header.tpl.html
- src/selectize/select-multiple.tpl.html
- src/selectize/select.tpl.html
- src/uiSelectDirective.js
- src/uiSelectFooterDirective.js
- src/uiSelectHeaderDirective.js
- test/select.spec.js
This feature allows to add header & footer to the dropdowns for each of the default templates.
> feat(Header & Footer): Add header & footer to the dropdown list.

- src/uiSelectController.js
- test/select.spec.js
( not from body, if I set attribute `append-to-body=true`)
> fix(uiSelectCtrl) calculateContainerWidth use width of ui-select-container

- src/common.js
- src/uiSelectController.js
- src/uiSelectMultipleDirective.js
- src/uiSelectSingleDirective.js
- test/select.spec.js
> fix(uiSelectMatch): set model value to `null` when cleared

- src/uiSelectFooterDirective.js
- src/uiSelectHeaderDirective.js
> (fix) injectables error in header and footer.

- src/bootstrap/select-multiple.tpl.html
- test/select.spec.js
The multiple mode would not show a refresh spinner even with spinner-enabled set to true. Add the same spinner html from the single selection template to the multiple selection template.
Closes #1985
> fix(spinner): add the refresh spinner to the select-multiple template

- src/bootstrap/select-multiple.tpl.html
- src/select2/select-multiple.tpl.html
- src/selectize/select-multiple.tpl.html
- src/uiSelectController.js
- src/uiSelectMultipleDirective.js
- test/select.spec.js
User can provide their custom `getPlaceholder()` function. E.g. to keep placeholder activated in multipleSelect component, you can use this one:
```
angular.module('myApp').directive('myAppUiSelectPlaceholderAlwaysVisible', function() {
return {
require: 'uiSelect',
link: function($scope, $element, attrs, $select) {
$select.getPlaceholder = function () {
return $select.placeholder;
}
}
}
});
```
And then add this directive to the `<ui-select>` html element
closes #1796
> fix($selectMultiple): allow user to override `getPlaceholder()` Behavior

- src/uiSelectDirective.js
- test/select.spec.js
As of now, a click event-handler on the `$document` is responsible for closing an open drop-down.
The click-event stops bubbling when `stopPropagation()` is called anywhere on the DOM before the `$document`. This breaks the closing of the drop-down. 
Registering the event-listener in the capture phase instead of the bubble phase fixes this bug.
Failing use-case: http://plnkr.co/edit/MWOhIKdUNpoQK5OWTC5G
Fixed use-case: http://plnkr.co/edit/jC2R9QJGUrbzljr0YR1C
I tested the examples and they're still working with my proposed solution. Tests are also succeeding, including the one i added. 
Angular version used downstream: v1.5.11
angular-ui version used downstream: 0.19.4
> fix: close drop-down regardless of `stopPropagation()` calls

- src/uiSelectController.js
This fix ensures that the dropdown actually is open before calling
_ensureHighlightVisible.
I didn't manage do reproduce the issue meaningfully in a test in the time I have available, but I think the change is quite obvious.
Here's a plunkr with the fix:
http://plnkr.co/edit/iV43PiaAzk0paO0ElZzT?p=preview
Fixes: #2050
> fix(uiSelectCtrl): ensureHighlightVisible triggered with closed dropdown

- src/bootstrap/choices.tpl.html
- src/common.css
- src/uiSelectController.js
- src/uiSelectHeaderGroupSelectableDirective.js
- test/select.spec.js
User can now select header of group by option to select all item in this group
#1074 old pull request ref
> feat(choices): allow user select group header

- docs/examples/demo-header-and-footer.html
- src/bootstrap/choices.tpl.html
- src/bootstrap/footer.tpl.html
- src/bootstrap/header.tpl.html
- src/bootstrap/select-multiple.tpl.html
- src/bootstrap/select.tpl.html
- src/common.css
- src/select2/footer.tpl.html
- src/select2/header.tpl.html
- src/select2/select-multiple.tpl.html
- src/select2/select.tpl.html
- src/selectize/choices.tpl.html
- src/selectize/footer.tpl.html
- src/selectize/header.tpl.html
- src/selectize/select-multiple.tpl.html
- src/selectize/select.tpl.html
- src/uiSelectDirective.js
- src/uiSelectFooterDirective.js
- src/uiSelectHeaderDirective.js
- test/select.spec.js
This feature allows to add header & footer to the dropdowns for each of the default templates.
> feat(Header & Footer): Add header & footer to the dropdown list - iteration 2.
