angular-ui/ui-select

src/select.js
This addresses issue #623, which is specific to tagging.  I verified the change against the basic demo.html file and there is no impact.
I also checked this change against the various Plunker in #520 and their respective issues are no longer there.
=> Only allow highlighted dropdown item to be selected using ENTER.

src/bootstrap/choices.tpl.html, src/select2/choices.tpl.html, src/selectize/choices.tpl.html
ng-bind-html requires sanitization of passed conent. It is not always possible and desired.
=> fix(templates): use ng-bind instead of ng-bind-html

src/bootstrap/match.tpl.html
Remove the outline and box shadow that comes with the btn class.
=> Add btn-link CSS class for Bootstrap clear button.

src/select.js, test/select.spec.js
This allows directives to include uiSelect and add parsers/formatters to ngModel
=> fix(ngModel) Allow uiSelect ngModel to populate from parent directive.

src/select.css
=> fix(bootstrap): reduce caret height to avoid wrong shadow

src/uiSelectController.js
Caused by https://github.com/angular/angular.js/pull/9720
Closes https://github.com/angular-ui/ui-select/issues/680
=> fix(uiSelectController): controller variables with correct default values

src/uiSelectController.js, src/uiSelectMultipleDirective.js
TypeError: Cannot read property 'length' of undefined
at uis.directive.controller.ctrl.getPlaceholder (select.js:1078)
at $parseFunctionCall (angular.js:12404)
at Object.expressionInputWatch (angular.js:12813)
at Scope.$get.Scope.$digest (angular.js:14300)
at Scope.$get.Scope.$apply (angular.js:14571)
at angular.js:16308
at completeOutstandingRequest (angular.js:4924)
at angular.js:5312
=> Solving bug when selectItems is undefined.

examples/demo-event-on-select.html, examples/demo.js
I have just tweaked the function that handles the select event in the examples to have a slightly friendlier name and updated the reference in the relevant ui-select element. Thought it would make it clearer for new-comers to find! Cheers :)
=> Minor function name tweak

README.md, composer.json
Package have been tested installable through composer package management.
- https://packagist.org/packages/components/ui-select
=> Add to composer package

src/uiSelectDirective.js
attr.limit should be an observable property so that it is
updatable after initialization
=> feat(limit): Change multi-select limit attr

CONTRIBUTING.md
Found a spelling mistake
`coordially` → `cordially`
=> docs(CONTRIBUTING): fix a typo

src/uiSelectController.js
Fixes https://github.com/angular-ui/ui-select/issues/1415
=> Prevent error when used with angular-animate <1.4 (Fixes #1415)

src/uiSelectController.js, src/uisDebounceService.js
- The resize event fires often, so debouncing the function execution can
improve performance dramatically
=> feat(perf): debounce resize callback

src/uiSelectController.js
- Properly garbage collect resize handler when directive is destroyed
- Properly debounce callback
=> fix: properly gc on destruction

src/uiSelectSingleDirective.js, test/select.spec.js
=> fix(uiSelectSingleDirective): strictly compare matching value

src/uiSelectController.js
perf: change test in ctrl.isActive
before :
( itemIndex < 0 && ctrl.taggingLabel !== false ) ||( itemIndex < 0 && ctrl.taggingLabel === false)
after :
itemIndex < 0
=> perf: change test in ctrl.isActive

src/uiSelectController.js, test/select.spec.js
loop through all `taggingTokens` and use first token that is contained in paste data for splitting (previously only first token was used)
Closes #1566
=> fix (tagging): try all taggingTokens for splitting on paste

src/bootstrap/choices.tpl.html
=> fix(bootstrap): hide dropdown if there are no items to show

src/uiSelectMultipleDirective.js, src/uiSelectSingleDirective.js
=> fix(parserResult): Ignore undefined parserResult when using custom tpl

docs/examples/demo-tagging.html
The tagging demo page not works since the use of the controller as in documentation.
=> Correct the tagging demo page

src/selectize/no-choice.tpl.html, src/selectize/select.tpl.html
https://github.com/angular-ui/ui-select/issues/1608
adding no-choice.tpl.html for Selectize theme.
=> fix(uiSelectNoChoice): support Selectize theme

src/uiSelectController.js, test/select.spec.js
This will fix #1760 
Still I don't have any tests @user378230  any thoughts on this.
Did try some stuff but didn't succeed.
=> fix(resetSearchInput) multiple didn't clear after selecting

src/bootstrap/select-multiple.tpl.html
=> Added aria-expanded to the multiple select template

CONTRIBUTING.md, README.md
=> Added PRs Welcome

src/uiSelectController.js, test/select.spec.js
=> fix(activeIndex) reset active option on clear model

.travis.yml, package.json
This PR should fix the problems we have on the TravisCI.
Still I don't know what changed maybe something in travis.
=> CI(Travis) fixing the travis build.

src/common.css
=> Fix border radius when using with input-group
